const DEFAULT_ENVIRONMENT = 'development';
const SERVER_PORT = 3000;
const DEFAULT_PAGE = 0;
const PAGE_LIMIT = 20;

export {
    DEFAULT_ENVIRONMENT,
    SERVER_PORT,
    DEFAULT_PAGE,
    PAGE_LIMIT
};
